name: Self Hosted Runner Workflow

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Test runner
        run: |
          echo "Running on : $HOSTNAME"
          echo "Working directory: $PWD"

